#!/bin/bash

# ==================== Cloudflare Setup Script ====================
# Configures Cloudflare DNS and security settings

set -e

echo "========================================="
echo "Cloudflare Setup Guide"
echo "========================================="
echo ""
echo "This script will guide you through Cloudflare setup"
echo ""

read -p "Enter your domain name: " DOMAIN
read -p "Enter your VPS IP address: " VPS_IP

echo ""
echo "========================================="
echo "STEP 1: Add Domain to Cloudflare"
echo "========================================="
echo "1. Go to https://dash.cloudflare.com"
echo "2. Click 'Add a Site'"
echo "3. Enter your domain: $DOMAIN"
echo "4. Select the Free plan"
echo "5. Cloudflare will scan your DNS records"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 2: Configure DNS Records"
echo "========================================="
echo "Add these DNS records in Cloudflare:"
echo ""
echo "Type  | Name  | Content       | Proxy Status"
echo "------|-------|---------------|-------------"
echo "A     | @     | $VPS_IP       | Proxied (Orange)"
echo "A     | www   | $VPS_IP       | Proxied (Orange)"
echo "A     | api   | $VPS_IP       | Proxied (Orange)"
echo ""
echo "Make sure 'Proxy status' is ORANGE (Proxied) for all records"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 3: Update Nameservers"
echo "========================================="
echo "1. Cloudflare will show you 2 nameservers"
echo "2. Go to your domain registrar (Namecheap, GoDaddy, etc.)"
echo "3. Update your domain's nameservers to Cloudflare's nameservers"
echo "4. Wait for propagation (can take up to 24 hours)"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 4: Configure SSL/TLS"
echo "========================================="
echo "1. In Cloudflare Dashboard, go to SSL/TLS"
echo "2. Set encryption mode to 'Full (strict)'"
echo "3. Enable 'Always Use HTTPS'"
echo "4. Enable 'Automatic HTTPS Rewrites'"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 5: Security Settings"
echo "========================================="
echo "Go to Security > Settings and configure:"
echo ""
echo "1. Security Level: Medium or High"
echo "2. Challenge Passage: 30 minutes"
echo "3. Browser Integrity Check: ON"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 6: Firewall Rules (Optional)"
echo "========================================="
echo "Create firewall rules to block malicious traffic:"
echo ""
echo "1. Go to Security > WAF > Firewall rules"
echo "2. Click 'Create firewall rule'"
echo ""
echo "Example Rule: Block Known Bots"
echo "  Field: Known Bots"
echo "  Operator: equals"
echo "  Value: On"
echo "  Action: Block"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 7: Rate Limiting (Optional)"
echo "========================================="
echo "Set up rate limiting to prevent abuse:"
echo ""
echo "1. Go to Security > WAF > Rate limiting rules"
echo "2. Click 'Create rate limiting rule'"
echo ""
echo "Example: API Rate Limit"
echo "  If: URI Path contains '/api/'"
echo "  Then: Requests per 10 seconds > 100"
echo "  Action: Block"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 8: Page Rules (Optional)"
echo "========================================="
echo "Optimize caching with page rules:"
echo ""
echo "1. Go to Rules > Page Rules"
echo "2. Create these rules:"
echo ""
echo "Rule 1: Cache Static Assets"
echo "  URL: *.$DOMAIN/*.{jpg,jpeg,png,gif,css,js}"
echo "  Settings: Cache Level = Cache Everything"
echo ""
echo "Rule 2: Bypass Cache for API"
echo "  URL: *.$DOMAIN/api/*"
echo "  Settings: Cache Level = Bypass"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "STEP 9: Enable Additional Features"
echo "========================================="
echo ""
echo "Speed > Optimization:"
echo "  ✓ Auto Minify (JS, CSS, HTML)"
echo "  ✓ Brotli"
echo "  ✓ Early Hints"
echo "  ✓ HTTP/2 to Origin"
echo "  ✓ HTTP/3 (with QUIC)"
echo ""
echo "Caching > Configuration:"
echo "  ✓ Browser Cache TTL: 4 hours"
echo "  ✓ Always Online: ON"
echo ""
read -p "Press Enter when done..."

echo ""
echo "========================================="
echo "Setup Complete!"
echo "========================================="
echo ""
echo "Your domain is now protected by Cloudflare with:"
echo "  ✓ DDoS Protection"
echo "  ✓ SSL/TLS Encryption"
echo "  ✓ CDN (Content Delivery Network)"
echo "  ✓ Web Application Firewall (WAF)"
echo "  ✓ Rate Limiting"
echo "  ✓ Caching & Performance Optimization"
echo ""
echo "Test your setup:"
echo "  https://$DOMAIN"
echo "  https://www.$DOMAIN"
echo "  https://api.$DOMAIN"
echo ""
echo "Check SSL rating: https://www.ssllabs.com/ssltest/analyze.html?d=$DOMAIN"
echo ""
